@host = https://localhost:7777

GET{{{{host}}}}/api/users
Accept: application/json

###
POST {{host}}/api/user
Content-type: application/json
{
    "id": 1,
    "name": "somename",
    "email": "dima@mydomain.edu"
}